### ISSUE TITLE
doesn't go into subsequent directories

### ISSUE THREAD

**Issue by harryalbert** [kieran-osgood/vscode-open-files-in-directory#1]
I have a folder with multiple subfolders, but the extension doesn't enter into these subfolders to open the files within them.  It only opens the surface level files

**Comment by kieran-osgood** [comment]
Hey @harryalbert!
If you go to your settings and check you've got the recursive setting to at least 1:
![image](https://user-images.githubusercontent.com/17687552/111188919-7729da00-85ad-11eb-856a-f41311c98c09.png)
And when you right click the directory there is actually a second button to open the folders nested, so you don't always go recursive:
![image](https://user-images.githubusercontent.com/17687552/111188955-7f821500-85ad-11eb-9b71-5ccd47904ccd.png)

Let me know if you're still having issues after trying this :)

**Comment by harryalbert** [comment]
Ah, I completely missed that.  thanks for the quick response!
