### ISSUE TITLE
Bug: Commands fail in multi-root workspaces

### ISSUE THREAD

**Issue by ingoaltair** [kieran-osgood/vscode-open-files-in-directory#3]
I have a folder full of python files (and some pyc), trying both recursive and normal opening all files does just nothing. There is no error message. 
I was so happy, I found this extension, so disappointed I can't use it.
Installation seemed to work fine and context menu entries (Open all..., Recursively Open all...) both appear. 
Am I missing anything?

**Comment by ingoaltair** [comment]
I think, I found the problem. I have a multi-root workspace. In that, only folders in the first root work. Probably an issue with pretending the root path?

**Comment by ingoaltair** [comment]
Ok, after installing like 5 similar extensions, I finally found "Open Multiple Files" from "Fabio Spampinato" to actually work. And even more, it has the one feature, that I was missing: filtering, so you don't load pyc file and similar.

**Comment by kieran-osgood** [comment]
Thanks for coming back with your extra information.
I have never used a multi-root setup so I'll look into that soon, and try to fix that area.
Will also look at adding a filtering setup too :)

**Comment by kieran-osgood** [comment]
Well time got away from me with starting a new job, but I just published an update in v1.0.2 which I hope fixes it, I don't have a windows machine to hand (will have one in 2-3 weeks so will double check then)

**Comment by kieran-osgood** [comment]
I finally got access to a windows machine, so I believe this should (finally) be resolved in v1.0.4!
