### ISSUE TITLE
Can't read Directory. Error: ENOENT: no such file or directory, scandir 'C:\c:\...'

### ISSUE THREAD

**Issue by Lx** [kieran-osgood/vscode-open-files-in-directory#5]
Right-clicking a folder in my workspace and clicking "Recursively open all files in directory", I get a popup error (where I have replaced some folder names with "..."):

> Can't read Directory. Error: ENOENT: no such file or directory, scandir 'C:\c:\Users\\...\\...\\...'

Of particular note is the duplication of `C:\` in the path, which explains why the operation fails.

Problem exists in extension version 1.0.0.

**Comment by kieran-osgood** [comment]
I finally got access to a windows machine, so I believe this should (finally) be resolved in v1.0.4!
