### ISSUE TITLE
[v1.0.4, macOS] Recursive opens only top level

### ISSUE THREAD

**Issue by Lx** [kieran-osgood/vscode-open-files-in-directory#6]
On macOS, running v1.0.4, I ensured appropriate extension settings then attempted to recursively open a folder.  Only the one file opened.  Attached video shows:

- the file layout
- the extension version
- the extension settings
- the failure to open more than one file.

https://user-images.githubusercontent.com/160164/182007967-7cb4abb8-8adc-4044-a46c-0171fcf2af9b.mov

**Comment by Lx** [comment]
A very, *very* similar extension [here](https://github.com/EuroCent82/vsc-open-all-files-in-directory) (which [almost definitely looks like it may have originated from your work, but with all credit to you removed](https://github.com/EuroCent82/vsc-open-all-files-in-directory/commit/f1853ad38382110adf412e4a6b8700610036c84c#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626)) works as expected on my machine.

**Comment by kieran-osgood** [comment]
Really appreciate the detailed issue, and notifying me of the other project, it's a shame they didn't just submit a PR to help fix it but to each their own!

I see in the 'forked' version from @EuroCent82 that it's just interpolating the filepath, which I feel would be broken on windows so want to narrow down the best way to handle it with VS api. 

Yesterday I was sorting windows pathing, so not sure if thats where it broke on macOS for you (I might just get a windows VM so I can fix it on both without breaking 🙃).

Good news though! Whilst I wasn't able to reproduce in a similar way to you, playing around this morning noticed some clear issues, I just published v1.0.5 which I think should be a lot better, switched from the node fs library to vscode.fs which is what they recommend (didn't know this at the time) - so I'm hoping this should be better.

**Comment by Lx** [comment]
I apparently have v1.0.7 now so I can't specifically comment on the v1.0.5 mentioned above, but I can confirm that the current version is working perfectly.  Many thanks!

**Comment by kieran-osgood** [comment]
> I apparently have v1.0.7 now so I can't specifically comment on the v1.0.5 mentioned above, but I can confirm that the current version is working perfectly.  Many thanks!

Awesome thanks for checking back in! I switched over to using vscode fs library as its their recommended approach now - might look to add more features going forwards for things like filtering file patterns
