### ISSUE TITLE
Use commands in opened file

### ISSUE THREAD

**Issue by ciscoheat** [kieran-osgood/vscode-open-files-in-directory#8]
Hi, would it be possible to use the commands with the currently opened file? For example, when I'm working with a file I realize that I would need to check a sibling file, I press `Ctrl+Shift+P`, choose the "Open all files in directory", but then I get an error message at the bottom right: `Open a file to open its sibling files`.

It would be nice if the command used the directory of the current file and opened all files in there.

**Comment by kieran-osgood** [comment]
This should be closed as part of v1.0.8 that has just published - should be available soon - please reopen if still experiencing issues!
